### ISSUE TITLE
Help URL Pattern JCE 2.8.4

### ISSUE THREAD

**Issue by ghost** [widgetfactory/jce-docs#1]
Help URL Pattern

Ryan please add screenshot of working real example how to configure using the syntax $1/$2/$3 ?

**Comment by ryandemmer** [comment]
This repo is not related to the JCE Editor Help screen.

Please post JCE releated support questions in the Support Forum - https://www.joomlacontenteditor.net/support/forum

**Comment by ryandemmer** [comment]
This repo is not currently actively used for the JCE Editor Help system.
